name: Push and PR

on:
  push:
  pull_request:
    types: [opened]

jobs:
  print-hello:
    if: ${{ github.event.action }} == 'opened'
    runs-on: ubuntu-latest

    steps:
      - name: print hello
        run: echo 'hello'

  print-world:
    runs-on: ubuntu-latest

    steps:
      - name: print world
        run: echo 'world'
