name: Push and PR

on:
  push:
  pull_request:
    types: [opened]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: print hello world
        run: echo 'hello world'

  print-action:
    runs-on: ubuntu-latest

    steps:
      - name: print action
        run: echo ${{ github.event.action }}
